export const FETCH_RECIPE_START = "FETCH_RECIPE_START";
export const FETCH_RECIPE_SUCCESS = "FETCH_RECIPE_SUCCESS";
export const FETCH_RECIPE_ERROR = "FETCH_RECIPE_ERROR";
export const UPDATE_RECIPE_SERVINGS = "UPDATE_RECIPE_SERVINGS";

export const SEARCH_START = "SEARCH_START";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";

export const INIT_LIKES = "INIT_LIKES";
export const ADD_LIKE = "ADD_LIKE";
export const REMOVE_LIKE = "REMOVE_LIKE";

export const ADD_SHOPPING_LIST_ITEM = "ADD_SHOPPING_LIST_ITEM"
export const REMOVE_SHOPPING_LIST_ITEM = "REMOVE_SHOPPING_LIST_ITEM"
export const UPDATE_SHOPPING_LIST_ITEM_COUNT = "UPDATE_SHOPPING_LIST_ITEM_COUNT";
